### ISSUE TITLE
Added columns are not displayed in map view upon re-import

### ISSUE THREAD

**Issue by RobinGoix** [systragroup/quetzal-network-editor#184]
When I add a new column through the DataFrame interface, I can use it in the map view, just as other default columns (to sort links, edit data attribute, etc.)
However, if I export then import the project, the new column is still available in the dataframe view, but not in the map view (even for attribute edition).

Attached is an example of such a network with the added column "vehicle_speed". 
[output (24).zip](https://github.com/systragroup/quetzal-network-editor/files/10024022/output.24.zip)

**Comment by sboivinsystra** [comment]
The problem here is that we have Line attributes and links attributes. For example, the travel time and length are links attributes and the headway is a line attribute. The line attribute are hardcoded.

We could either
1) add the list of line attributes in the settings (so it's editable) and maybe export the setting in the output.zip.
2) display every fields as editable with with a "multiple values" when there is multiple values

**Comment by RobinGoix** [comment]
Hi Simon, I would personally prefer the 2nd option (which I think is already the one assumed when adding a new field). I find it simpler (it lets the user do whatever he wants and does not requires an additional settings file).
