### ISSUE TITLE
Feature request: search bar for lines

### ISSUE THREAD

**Issue by JeffLEDGE** [systragroup/quetzal-network-editor#476]
Would make things easier than scrolling through all the lines or even a single agency's lines to find one.

**Comment by sboivinsystra** [comment]
do you imagine, a seach bar where the clicked trip go into edition?

or else, i could add a "seach bar" in the filter menu items list.
![image](https://github.com/systragroup/quetzal-network-editor/assets/79281989/936990a2-2002-4a38-91da-75e5ccee2424)

and the trips list would be the one matching what is typed instead of "agency_id" for example.

**Comment by sboivinsystra** [comment]
5.1.j only prefix tho

![image](https://github.com/systragroup/quetzal-network-editor/assets/79281989/51abee36-879c-4cba-8096-61ba6d07381c)
